# Generated by Django 5.2.6 on 2025-09-22 06:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='auto_release_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='buyer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='creation_tx_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='escrow',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='escrow_contract_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='escrow_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20),
        ),
        migrations.AddField(
            model_name='escrow',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='escrow',
            name='release_tx_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='escrow',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='seller_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_escrows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='currency',
            field=models.CharField(default='NCR', max_length=10),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='escrow_address',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('auto_released', 'Auto Released')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['status', 'created_at'], name='marketplace_status_85e680_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['escrow_contract_id'], name='marketplace_escrow__fca8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['auto_release_time'], name='marketplace_auto_re_0264d4_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['dispute_deadline'], name='marketplace_dispute_71670f_idx'),
        ),
    ]
